version: "3.9"
services:
  datastore:
    build:
      context: datastore-dev
    volumes:
      - ./src/main/appengine/index.yaml:/root/.config/gcloud/emulators/datastore/WEB-INF/index.yaml
    ports:
      - 8484:8484
  solr:
    build:
      context: solr
    ports:
      - 8983:8983
  postgres:
    image: postgres:14.4
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teammates
      POSTGRES_PASSWORD: teammates
      POSTGRES_DB: teammates
