name: Pull Request Checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - pr-workflow

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
          const isTitleValid = /^[#\\d] /.test(pr.data.title)
          const isDescriptionValid = /(Fixes|Part of) #\\d/.test(pr.data.body)
          if (isTitleValid && isDescriptionValid) {
            return
          }
          let body = `Hi @${pr.data.user.login}, thank you for your interest in contributing to TEAMMATES!
            However, your PR does not appear to follow our [contribution guidelines](docs/CONTRIBUTING.md):\n\n`
          if (!isTitleValid) {
            body += "- Title must start with the issue number the PR is fixing, e.g. `[#<issue-number>]`\n"
          }
          if (!isDescriptionValid) {
            body += "- Description must reference the issue number the PR is fixing, e.g. `Fixes/Part of #<issue-number>`\n"
          }
          body += "\nPlease address the above before we proceed to review your PR."
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body,
          })
