name: Pull Request Checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - pr-workflow

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
          console.log(pr)
